version: '3.8'

services:
  postgres:
    image: postgres:15.1
    restart: always
    environment:
        - POSTGRES_USER=orange
        - POSTGRES_PASSWORD=hellojohn
        - POSTGRES_DB=orangedb
    volumes:
        - ./data/postgres:/var/postgresql/data
    ports:
        - '54322:5432'